branches:
  only:
    - main
language: node_js
node_js:
  - 12

services:
  - docker

script:
  ## Build docker
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker-compose -f docker-compose-build.yaml build
  ## Tagging
  - docker tag udagram-api-feed vainres/udagram-api-feed:v1
  - docker tag udagram-api-user vainres/udagram-api-user:v1
  - docker tag udagram-frontend vainres/udagram-frontend:v1
  - docker tag udagram-reverseproxy vainres/udagram-reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  ## Push
  - docker push vainres/udagram-api-feed:v1
  - docker push vainres/udagram-api-user:v1
  - docker push vainres/udagram-frontend:v1
  - docker push vainres/udagram-reverseproxy:v1