apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: "vainres/udagram-frontend:v4"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-secret
              readOnly: true
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret